package org.kie.example.traffic.traffic_violation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class jartest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public jartest() {
    }




}