package org.kie.example.traffic.traffic_violation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String dog;

	private java.lang.String cat;

	public test() {
	}

	public java.lang.String getDog() {
		return this.dog;
	}

	public void setDog(java.lang.String dog) {
		this.dog = dog;
	}

	public java.lang.String getCat() {
		return this.cat;
	}

	public void setCat(java.lang.String cat) {
		this.cat = cat;
	}

	public test(java.lang.String dog, java.lang.String cat) {
		this.dog = dog;
		this.cat = cat;
	}

}